### ISSUE TITLE
Análisis Requerimientos #R6

### ISSUE THREAD

**Issue by razerr17** [razerr17/Compumundo_Hiper_Mega_Red_G4#2]
Realizar los modelos SD y SR del requerimiento:
R6)a) Determinar el diagnóstico académico de los estudiantes bajo su tutoría, basándose en el
Avance Curricular de los estudiantes que hayan repetido dos veces una asignatura.

**Comment by etson32** [comment]
[R06-SR-SD.txt](https://github.com/razerr17/Compumundo_Hiper_Mega_Red_G4/files/6781572/R06-SR-SD.txt)
Tanto el SD y SR
