### ISSUE TITLE
Análisis Requerimientos #R5

### ISSUE THREAD

**Issue by razerr17** [razerr17/Compumundo_Hiper_Mega_Red_G4#4]
Realizar los modelos SD y SR del requerimiento:
R5)Programar y publicar en físico y en el Portal Web de la Escuela Profesional el horario y aulas donde se realizarán los talleres de reforzamiento académico para las diferentes asignaturas que sean necesarias, para los estudiantes en riesgo académico, los mismos que serán realizados por los Estudiantes Ayudantes de Tutoría, de acuerdo a lo señalado en el Art. 17o,inciso d).

**Comment by CarlosEdu322** [comment]
> Realizar los modelos SD y SR del requerimiento:
> R5)Programar y publicar en físico y en el Portal Web de la Escuela Profesional el horario y aulas donde se realizarán los talleres de reforzamiento académico para las diferentes asignaturas que sean necesarias, para los estudiantes en riesgo académico, los mismos que serán realizados por los Estudiantes Ayudantes de Tutoría, de acuerdo a lo señalado en el Art. 17o,inciso d).

**Comment by CarlosEdu322** [comment]
Requerimiento 5:
[RQ5.txt](https://github.com/razerr17/Compumundo_Hiper_Mega_Red_G4/files/6785885/RQ5.txt)
